// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { NoahToken$Type } from "./NoahToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NoahToken"]: NoahToken$Type;
    ["contracts/NoahToken.sol:NoahToken"]: NoahToken$Type;
  }
}
